# Generated by Django 3.2.5 on 2022-06-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterField(
            model_name='project',
            name='fluid',
            field=models.CharField(choices=[('1-Butene', '1-Butene'), ('Acetone', 'Acetone'), ('Air', 'Air'), ('Ammonia', 'Ammonia'), ('Argon', 'Argon'), ('Benzene', 'Benzene'), ('CarbonDioxide', 'CarbonDioxide'), ('CarbonMonoxide', 'CarbonMonoxide'), ('CarbonylSulfide', 'CarbonylSulfide'), ('CycloHexane', 'CycloHexane'), ('CycloPropane', 'CycloPropane'), ('Cyclopentane', 'Cyclopentane'), ('D4', 'D4'), ('D5', 'D5'), ('D6', 'D6'), ('Deuterium', 'Deuterium'), ('Dichloroethane', 'Dichloroethane'), ('DiethylEther', 'DiethylEther'), ('DimethylCarbonate', 'DimethylCarbonate'), ('DimethylEther', 'DimethylEther'), ('Ethane', 'Ethane'), ('Ethanol', 'Ethanol'), ('EthylBenzene', 'EthylBenzene'), ('Ethylene', 'Ethylene'), ('EthyleneOxide', 'EthyleneOxide'), ('Fluorine', 'Fluorine'), ('HFE143m', 'HFE143m'), ('HeavyWater', 'HeavyWater'), ('Helium', 'Helium'), ('Hydrogen', 'Hydrogen'), ('HydrogenChloride', 'HydrogenChloride'), ('HydrogenSulfide', 'HydrogenSulfide'), ('IsoButane', 'IsoButane'), ('IsoButene', 'IsoButene'), ('Isohexane', 'Isohexane'), ('Isopentane', 'Isopentane'), ('Krypton', 'Krypton'), ('MD2M', 'MD2M'), ('MD3M', 'MD3M'), ('MD4M', 'MD4M'), ('MDM', 'MDM'), ('MM', 'MM'), ('Methane', 'Methane'), ('Methanol', 'Methanol'), ('MethylLinoleate', 'MethylLinoleate'), ('MethylLinolenate', 'MethylLinolenate'), ('MethylOleate', 'MethylOleate'), ('MethylPalmitate', 'MethylPalmitate'), ('MethylStearate', 'MethylStearate'), ('Neon', 'Neon'), ('Neopentane', 'Neopentane'), ('Nitrogen', 'Nitrogen'), ('NitrousOxide', 'NitrousOxide'), ('Novec649', 'Novec649'), ('OrthoDeuterium', 'OrthoDeuterium'), ('OrthoHydrogen', 'OrthoHydrogen'), ('Oxygen', 'Oxygen'), ('ParaDeuterium', 'ParaDeuterium'), ('ParaHydrogen', 'ParaHydrogen'), ('Propylene', 'Propylene'), ('Propyne', 'Propyne'), ('R11', 'R11'), ('R113', 'R113'), ('R114', 'R114'), ('R115', 'R115'), ('R116', 'R116'), ('R12', 'R12'), ('R123', 'R123'), ('R1233zd(E)', 'R1233zd(E)'), ('R1234yf', 'R1234yf'), ('R1234ze(E)', 'R1234ze(E)'), ('R1234ze(Z)', 'R1234ze(Z)'), ('R124', 'R124'), ('R1243zf', 'R1243zf'), ('R125', 'R125'), ('R13', 'R13'), ('R134a', 'R134a'), ('R13I1', 'R13I1'), ('R14', 'R14'), ('R141b', 'R141b'), ('R142b', 'R142b'), ('R143a', 'R143a'), ('R152A', 'R152A'), ('R161', 'R161'), ('R21', 'R21'), ('R218', 'R218'), ('R22', 'R22'), ('R227EA', 'R227EA'), ('R23', 'R23'), ('R236EA', 'R236EA'), ('R236FA', 'R236FA'), ('R245ca', 'R245ca'), ('R245fa', 'R245fa'), ('R32', 'R32'), ('R365MFC', 'R365MFC'), ('R40', 'R40'), ('R404A', 'R404A'), ('R407C', 'R407C'), ('R41', 'R41'), ('R410A', 'R410A'), ('R507A', 'R507A'), ('RC318', 'RC318'), ('SES36', 'SES36'), ('SulfurDioxide', 'SulfurDioxide'), ('SulfurHexafluoride', 'SulfurHexafluoride'), ('Toluene', 'Toluene'), ('Water', 'Water'), ('Xenon', 'Xenon'), ('cis-2-Butene', 'cis-2-Butene'), ('m-Xylene', 'm-Xylene'), ('n-Butane', 'n-Butane'), ('n-Decane', 'n-Decane'), ('n-Dodecane', 'n-Dodecane'), ('n-Heptane', 'n-Heptane'), ('n-Hexane', 'n-Hexane'), ('n-Nonane', 'n-Nonane'), ('n-Octane', 'n-Octane'), ('n-Pentane', 'n-Pentane'), ('n-Propane', 'n-Propane'), ('n-Undecane', 'n-Undecane'), ('o-Xylene', 'o-Xylene'), ('p-Xylene', 'p-Xylene'), ('trans-2-Butene', 'trans-2-Butene')], max_length=20, verbose_name='Fluid'),
        ),
    ]
