# Generated by Django 3.2.5 on 2022-06-10 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piping', '0003_auto_20220610_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory', models.CharField(choices=[('straight_pipe', 'Straight pipe'), ('bend_rounded', 'Bend rounded'), ('K_angle_stop_check_valve_Crane', 'Angle stop check valve'), ('K_angle_valve_Crane', 'Angle valve'), ('K_ball_valve_Crane', 'Ball valve'), ('K_butterfly_valve_Crane', 'Butterfly valve'), ('K_diaphragm_valve_Crane', 'Diaphragm valve'), ('K_foot_valve_Crane', 'Foot valve'), ('K_gate_valve_Crane', 'Gate valve'), ('K_globe_stop_check_valve_Crane', 'Globe stop check valve'), ('K_globe_valve_Crane', 'Globe valve'), ('K_lift_check_valve_Crane', 'Lift check valve'), ('K_plug_valve_Crane', 'Plug valve'), ('K_swing_check_valve_Crane', 'Swing check valve'), ('K_tilting_disk_check_valve_Crane', 'Tilting disk check valve')], max_length=50, verbose_name='Accessory')),
                ('material', models.CharField(choices=[('Rough wood stave', 'Rough wood stave'), ('Concrete', 'Concrete'), ('Brass', 'Brass'), ('Steel', 'Steel'), ('Lead', 'Lead'), ('Cr13, electropolished bare', 'Cr13, electropolished bare'), ('Carbon steel, honed bare', 'Carbon steel, honed bare'), ('Rough concrete', 'Rough concrete'), ('Cast iron', 'Cast iron'), ('Cement lining', 'Cement lining'), ('Fiberglass lining', 'Fiberglass lining'), ('Carbon steel, bare', 'Carbon steel, bare'), ('Asphalted cast iron', 'Asphalted cast iron'), ('Glass', 'Glass'), ('Galvanized iron', 'Galvanized iron'), ('Rough riveted steel', 'Rough riveted steel'), ('Wood stave', 'Wood stave'), ('Riveted steel', 'Riveted steel'), ('Cr13, bare', 'Cr13, bare'), ('Plastic coated', 'Plastic coated')], max_length=50, verbose_name='Material')),
                ('quantity', models.IntegerField(verbose_name='Quantity [m] or units')),
                ('inner_diameter', models.FloatField(verbose_name='Inner diameter [m]')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piping.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Pipe Accessory',
                'verbose_name_plural': 'Pipe Accesories',
            },
        ),
    ]
