# Generated by Django 3.2.5 on 2022-06-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piping', '0004_projectaccessory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'get_latest_by': 'name', 'ordering': ['-id'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='projectaccessory',
            options={'ordering': ['-id'], 'verbose_name': 'Pipe Accessory', 'verbose_name_plural': 'Pipe Accesories'},
        ),
        migrations.AlterField(
            model_name='projectaccessory',
            name='accessory',
            field=models.CharField(choices=[('straight_pipe', 'Straight pipe'), ('bend_rounded', 'Bend rounded'), ('diffuser_sharp', 'Diffuser sharp'), ('contraction_sharp', 'Contraction sharp'), ('K_angle_stop_check_valve_Crane', ''), ('K_angle_valve_Crane', ''), ('K_ball_valve_Crane', 'Angle stop check valve'), ('K_butterfly_valve_Crane', 'Angle valve'), ('K_diaphragm_valve_Crane', 'Ball valve'), ('K_foot_valve_Crane', 'Butterfly valve'), ('K_gate_valve_Crane', 'Diaphragm valve'), ('K_globe_stop_check_valve_Crane', 'Foot valve'), ('K_globe_valve_Crane', 'Gate valve'), ('K_lift_check_valve_Crane', 'Globe stop check valve'), ('K_plug_valve_Crane', 'Globe valve'), ('K_swing_check_valve_Crane', 'Lift check valve'), ('K_tilting_disk_check_valve_Crane', 'Plug valve')], max_length=50, verbose_name='Accessory'),
        ),
        migrations.AlterField(
            model_name='projectaccessory',
            name='material',
            field=models.CharField(choices=[('Plastic coated', 'Plastic coated'), ('Riveted steel', 'Riveted steel'), ('Lead', 'Lead'), ('Cast iron', 'Cast iron'), ('Galvanized iron', 'Galvanized iron'), ('Concrete', 'Concrete'), ('Rough riveted steel', 'Rough riveted steel'), ('Cr13, electropolished bare', 'Cr13, electropolished bare'), ('Cement lining', 'Cement lining'), ('Asphalted cast iron', 'Asphalted cast iron'), ('Carbon steel, honed bare', 'Carbon steel, honed bare'), ('Rough concrete', 'Rough concrete'), ('Carbon steel, bare', 'Carbon steel, bare'), ('Glass', 'Glass'), ('Cr13, bare', 'Cr13, bare'), ('Fiberglass lining', 'Fiberglass lining'), ('Brass', 'Brass'), ('Rough wood stave', 'Rough wood stave'), ('Wood stave', 'Wood stave'), ('Steel', 'Steel')], max_length=50, verbose_name='Material'),
        ),
    ]
