# Generated by Django 3.2.5 on 2022-06-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piping', '0005_auto_20220610_0615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-id'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='projectaccessory',
            name='angle',
            field=models.FloatField(blank=True, null=True, verbose_name='Inner diameter 2 [m]'),
        ),
        migrations.AddField(
            model_name='projectaccessory',
            name='inner_diameter2',
            field=models.FloatField(blank=True, null=True, verbose_name='Inner diameter 2 [m]'),
        ),
        migrations.AlterField(
            model_name='projectaccessory',
            name='material',
            field=models.CharField(choices=[('Rough wood stave', 'Rough wood stave'), ('Fiberglass lining', 'Fiberglass lining'), ('Asphalted cast iron', 'Asphalted cast iron'), ('Rough concrete', 'Rough concrete'), ('Cr13, bare', 'Cr13, bare'), ('Brass', 'Brass'), ('Concrete', 'Concrete'), ('Plastic coated', 'Plastic coated'), ('Carbon steel, bare', 'Carbon steel, bare'), ('Cast iron', 'Cast iron'), ('Lead', 'Lead'), ('Riveted steel', 'Riveted steel'), ('Cement lining', 'Cement lining'), ('Cr13, electropolished bare', 'Cr13, electropolished bare'), ('Carbon steel, honed bare', 'Carbon steel, honed bare'), ('Steel', 'Steel'), ('Galvanized iron', 'Galvanized iron'), ('Glass', 'Glass'), ('Rough riveted steel', 'Rough riveted steel'), ('Wood stave', 'Wood stave')], max_length=50, verbose_name='Material'),
        ),
    ]
